### ISSUE TITLE
Implement CRUD for Projects/Experiments/Variations

### ISSUE THREAD

**Issue by nsheaps** [FunnelEnvy/optimizely-node#2]
I'm writing a CLI utility similar to your optimizely-cli project and am looking to implement push AND pull functionality for experiments, variations and projects, but there's no Update defined for Projects, only Create and Read. Can you finish implementing CRUD methods for at least Projects, Experiments, and Variations?

Thanks!

**Comment by axs89** [comment]
Thanks for the feedback. This definitely needs to happen and we're working on the timing of finishing up the API. Always happy to take pull requests as well :)

**Comment by nselvidge** [comment]
@nsheaps this is fixed in #4
